<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Machine Learning – DSAN 6000 Big Data Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DSAN 6000 Big Data Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda.html"> 
<span class="menu-text">EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./nlp.html"> 
<span class="menu-text">NLP</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./ml.html" aria-current="page"> 
<span class="menu-text">ML</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conclusion.html"> 
<span class="menu-text">Conclusion</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#business-question-1-how-well-can-we-predict-reddit-post-engagement-log1score-using-only-content-at-posting-time-and-how-much-additional-predictive-power-comes-from-early-comment-activity" id="toc-business-question-1-how-well-can-we-predict-reddit-post-engagement-log1score-using-only-content-at-posting-time-and-how-much-additional-predictive-power-comes-from-early-comment-activity" class="nav-link" data-scroll-target="#business-question-1-how-well-can-we-predict-reddit-post-engagement-log1score-using-only-content-at-posting-time-and-how-much-additional-predictive-power-comes-from-early-comment-activity">Business Question 1 : How well can we predict Reddit post engagement (log(1+score)) using only content at posting time, and how much additional predictive power comes from early comment activity?</a>
  <ul class="collapse">
  <li><a href="#problem-formulation" id="toc-problem-formulation" class="nav-link" data-scroll-target="#problem-formulation">Problem Formulation</a></li>
  <li><a href="#model-performance-summary" id="toc-model-performance-summary" class="nav-link" data-scroll-target="#model-performance-summary">Model Performance Summary</a></li>
  <li><a href="#subreddit-level-performance" id="toc-subreddit-level-performance" class="nav-link" data-scroll-target="#subreddit-level-performance">Subreddit-Level Performance</a></li>
  <li><a href="#performance-shift-table" id="toc-performance-shift-table" class="nav-link" data-scroll-target="#performance-shift-table">Performance Shift Table</a></li>
  <li><a href="#interpretation-insights" id="toc-interpretation-insights" class="nav-link" data-scroll-target="#interpretation-insights">Interpretation &amp; Insights</a></li>
  <li><a href="#business-practical-implications" id="toc-business-practical-implications" class="nav-link" data-scroll-target="#business-practical-implications">Business &amp; Practical Implications</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  <li><a href="#business-question-2-can-we-classify-the-emotional-tone-of-reddit-posts-as-positive-negative-or-neutral-to-understand-public-sentiment-at-scale" id="toc-business-question-2-can-we-classify-the-emotional-tone-of-reddit-posts-as-positive-negative-or-neutral-to-understand-public-sentiment-at-scale" class="nav-link" data-scroll-target="#business-question-2-can-we-classify-the-emotional-tone-of-reddit-posts-as-positive-negative-or-neutral-to-understand-public-sentiment-at-scale">Business Question 2: Can we classify the emotional tone of Reddit posts as positive, negative, or neutral to understand public sentiment at scale?</a>
  <ul class="collapse">
  <li><a href="#problem-formulation-1" id="toc-problem-formulation-1" class="nav-link" data-scroll-target="#problem-formulation-1">Problem Formulation</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature Engineering</a></li>
  <li><a href="#model-performance" id="toc-model-performance" class="nav-link" data-scroll-target="#model-performance">Model Performance</a></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1">Summary</a></li>
  </ul></li>
  <li><a href="#business-question-3-can-we-identify-inauthentic-promotional-accounts-versus-genuine-users-in-audio-product-discussions" id="toc-business-question-3-can-we-identify-inauthentic-promotional-accounts-versus-genuine-users-in-audio-product-discussions" class="nav-link" data-scroll-target="#business-question-3-can-we-identify-inauthentic-promotional-accounts-versus-genuine-users-in-audio-product-discussions">Business Question 3: Can we identify inauthentic promotional accounts versus genuine users in audio product discussions?</a>
  <ul class="collapse">
  <li><a href="#problem-formulation-2" id="toc-problem-formulation-2" class="nav-link" data-scroll-target="#problem-formulation-2">Problem Formulation</a></li>
  <li><a href="#feature-engineering-user-behavioral-patterns" id="toc-feature-engineering-user-behavioral-patterns" class="nav-link" data-scroll-target="#feature-engineering-user-behavioral-patterns">Feature Engineering: User Behavioral Patterns</a></li>
  <li><a href="#suspicious-user-labeling" id="toc-suspicious-user-labeling" class="nav-link" data-scroll-target="#suspicious-user-labeling">Suspicious User Labeling</a></li>
  <li><a href="#model-performance-results" id="toc-model-performance-results" class="nav-link" data-scroll-target="#model-performance-results">Model Performance Results</a></li>
  <li><a href="#feature-importance-analysis" id="toc-feature-importance-analysis" class="nav-link" data-scroll-target="#feature-importance-analysis">Feature Importance Analysis</a></li>
  <li><a href="#key-insights" id="toc-key-insights" class="nav-link" data-scroll-target="#key-insights">Key Insights</a></li>
  <li><a href="#business-implications" id="toc-business-implications" class="nav-link" data-scroll-target="#business-implications">Business Implications</a></li>
  <li><a href="#summary-2" id="toc-summary-2" class="nav-link" data-scroll-target="#summary-2">Summary</a></li>
  </ul></li>
  <li><a href="#business-question-4-what-underlying-painpoint-clusters-exist-in-reddit-discussions-about-wireless-earbuds-and-how-do-these-clusters-differ-across-subreddits" id="toc-business-question-4-what-underlying-painpoint-clusters-exist-in-reddit-discussions-about-wireless-earbuds-and-how-do-these-clusters-differ-across-subreddits" class="nav-link" data-scroll-target="#business-question-4-what-underlying-painpoint-clusters-exist-in-reddit-discussions-about-wireless-earbuds-and-how-do-these-clusters-differ-across-subreddits">Business Question 4: What underlying painpoint clusters exist in Reddit discussions about wireless earbuds, and how do these clusters differ across subreddits?</a>
  <ul class="collapse">
  <li><a href="#problem-formulation-3" id="toc-problem-formulation-3" class="nav-link" data-scroll-target="#problem-formulation-3">Problem Formulation</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a></li>
  <li><a href="#cluster-results" id="toc-cluster-results" class="nav-link" data-scroll-target="#cluster-results">Cluster Results</a></li>
  <li><a href="#subreddit-level-patterns" id="toc-subreddit-level-patterns" class="nav-link" data-scroll-target="#subreddit-level-patterns">Subreddit-Level Patterns</a></li>
  <li><a href="#interpretation-insights-1" id="toc-interpretation-insights-1" class="nav-link" data-scroll-target="#interpretation-insights-1">Interpretation &amp; Insights</a></li>
  <li><a href="#summary-3" id="toc-summary-3" class="nav-link" data-scroll-target="#summary-3">Summary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Machine Learning</h1>
<p class="subtitle lead">Predictive Models and Classification</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This page presents machine learning models addressing 3 ML business questions through classification, regression, or clustering.</p>
</section>
<section id="business-question-1-how-well-can-we-predict-reddit-post-engagement-log1score-using-only-content-at-posting-time-and-how-much-additional-predictive-power-comes-from-early-comment-activity" class="level2">
<h2 class="anchored" data-anchor-id="business-question-1-how-well-can-we-predict-reddit-post-engagement-log1score-using-only-content-at-posting-time-and-how-much-additional-predictive-power-comes-from-early-comment-activity">Business Question 1 : How well can we predict Reddit post engagement (log(1+score)) using only content at posting time, and how much additional predictive power comes from early comment activity?</h2>
<hr>
<section id="problem-formulation" class="level3">
<h3 class="anchored" data-anchor-id="problem-formulation">Problem Formulation</h3>
<ul>
<li><strong>Task Type:</strong> Regression</li>
<li><strong>Target Variable:</strong> <code>log(1 + score)</code> of Reddit submissions</li>
<li><strong>Primary Metrics:</strong> R², RMSE, MAE</li>
</ul>
<p>We train two models:</p>
<ol type="1">
<li><p><strong>Model 1 — Content-Only (Causal Model)</strong></p>
<ul>
<li>Title + selftext (TF-IDF)</li>
<li>Subreddit (one-hot)</li>
<li>Text length features</li>
<li>Posting hour &amp; day of week</li>
</ul></li>
<li><p><strong>Model 2 — Content + Early Comments</strong></p>
<ul>
<li>All features from Model 1</li>
<li>Early comment count (first hour)</li>
<li>Average / max early comment score</li>
<li>Early comment length</li>
<li>Std deviation of early comment score</li>
</ul></li>
</ol>
<hr>
</section>
<section id="model-performance-summary" class="level3">
<h3 class="anchored" data-anchor-id="model-performance-summary">Model Performance Summary</h3>
<section id="global-metrics-comparison" class="level4">
<h4 class="anchored" data-anchor-id="global-metrics-comparison">Global Metrics Comparison</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>R²</th>
<th>RMSE</th>
<th>MAE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Content-Only</strong></td>
<td>0.1236</td>
<td>0.8288</td>
<td>0.4267</td>
</tr>
<tr class="even">
<td><strong>Content + Early Comments</strong></td>
<td><strong>0.4849</strong></td>
<td><strong>0.6186</strong></td>
<td><strong>0.2932</strong></td>
</tr>
</tbody>
</table>
<p><strong>Insight:</strong> Adding early comments improves R² by <strong>+0.36</strong>, showing early engagement is a strong predictor of eventual popularity.</p>
<hr>
</section>
</section>
<section id="subreddit-level-performance" class="level3">
<h3 class="anchored" data-anchor-id="subreddit-level-performance">Subreddit-Level Performance</h3>
<p>We compare errors for the top audio-related subreddits.</p>
<section id="model-1-content-only-rmse-by-subreddit" class="level4">
<h4 class="anchored" data-anchor-id="model-1-content-only-rmse-by-subreddit">Model 1 (Content-Only) — RMSE by Subreddit</h4>
<p><img src="../data/plots/ML_rmse_by_subreddit_model1_content_only.png" class="img-fluid"></p>
<p><strong>Key Observations:</strong></p>
<ul>
<li>Subreddits with highly focused product discussions (e.g., <code>bluetooth</code>, <code>audio</code>) are the easiest to predict.</li>
<li>Broad lifestyle/tech subs (<code>running</code>, <code>Android</code>, <code>headphones</code>) show larger variability → content alone is insufficient.</li>
</ul>
<hr>
</section>
<section id="model-2-content-early-comments-rmse-by-subreddit" class="level4">
<h4 class="anchored" data-anchor-id="model-2-content-early-comments-rmse-by-subreddit">Model 2 (Content + Early Comments) — RMSE by Subreddit</h4>
<p><img src="../data/plots/ML_rmse_by_subreddit_model2_early_comments.png" class="img-fluid"></p>
<p><strong>Key Observations:</strong></p>
<ul>
<li>All subreddits show <strong>substantial RMSE reduction</strong>.</li>
<li>Improvement is strongest for subs where engagement snowballs (e.g., <code>GooglePixel</code>, <code>headphones</code>).</li>
</ul>
<hr>
</section>
</section>
<section id="performance-shift-table" class="level3">
<h3 class="anchored" data-anchor-id="performance-shift-table">Performance Shift Table</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Subreddit</th>
<th>RMSE (M1)</th>
<th>RMSE (M2)</th>
<th>Improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bluetooth</td>
<td>0.287</td>
<td>0.189</td>
<td><strong>-0.098</strong></td>
</tr>
<tr class="even">
<td>audio</td>
<td>0.313</td>
<td>0.281</td>
<td><strong>-0.032</strong></td>
</tr>
<tr class="odd">
<td>Earbuds</td>
<td>0.373</td>
<td>0.358</td>
<td><strong>-0.015</strong></td>
</tr>
<tr class="even">
<td>bose</td>
<td>0.553</td>
<td>0.593</td>
<td>Slight increase (noisy category)</td>
</tr>
<tr class="odd">
<td>Samsung</td>
<td>0.929</td>
<td>0.658</td>
<td><strong>-0.271</strong></td>
</tr>
</tbody>
</table>
<p><strong>Takeaway:</strong> Most subreddits benefit significantly from early comments; a few high-variance product communities fluctuate more.</p>
<hr>
</section>
<section id="interpretation-insights" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-insights">Interpretation &amp; Insights</h3>
<section id="content-alone-is-only-mildly-predictive." class="level4">
<h4 class="anchored" data-anchor-id="content-alone-is-only-mildly-predictive.">1. <strong>Content alone is only mildly predictive.</strong></h4>
<ul>
<li>Engagement is influenced by timing, community mood, and hidden social factors.</li>
<li>Content-only R² ≈ 0.12 indicates limited determinism.</li>
</ul>
</section>
<section id="early-comments-act-as-a-strong-signal-amplifier." class="level4">
<h4 class="anchored" data-anchor-id="early-comments-act-as-a-strong-signal-amplifier.">2. <strong>Early comments act as a strong signal amplifier.</strong></h4>
<ul>
<li>Their presence captures social proof, visibility bump, and Reddit’s ranking feedback loop.</li>
<li>R² jumps to nearly 0.49 with early comment signals.</li>
</ul>
</section>
<section id="subreddit-heterogeneity-matters." class="level4">
<h4 class="anchored" data-anchor-id="subreddit-heterogeneity-matters.">3. <strong>Subreddit heterogeneity matters.</strong></h4>
<ul>
<li>Specialist product-focused communities behave more consistently.</li>
<li>Larger, more diverse subs require richer features to predict accurately.</li>
</ul>
<hr>
</section>
</section>
<section id="business-practical-implications" class="level3">
<h3 class="anchored" data-anchor-id="business-practical-implications">Business &amp; Practical Implications</h3>
<section id="for-platform-moderation-recommendation" class="level4">
<h4 class="anchored" data-anchor-id="for-platform-moderation-recommendation">For Platform Moderation / Recommendation</h4>
<ul>
<li>Early comments can identify potentially viral posts after <strong>1 hour</strong>.</li>
<li>Enables dynamic boosting or safety review workflows.</li>
</ul>
</section>
<section id="for-content-creators" class="level4">
<h4 class="anchored" data-anchor-id="for-content-creators">For Content Creators</h4>
<ul>
<li>Optimizing first-hour engagement (CTAs, clearer titles, early responder bots) can materially change outcomes.</li>
<li>Content-only model can help evaluate alternative titles <strong>before posting</strong>.</li>
</ul>
</section>
<section id="for-brandmarket-analysis" class="level4">
<h4 class="anchored" data-anchor-id="for-brandmarket-analysis">For Brand/Market Analysis</h4>
<ul>
<li>Subreddit-level predictability reveals <strong>which communities are stable vs.&nbsp;chaotic</strong>.</li>
<li>Useful for targeting product discussions or evaluating sentiment dynamics.</li>
</ul>
<hr>
</section>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<ul>
<li><strong>Model 1</strong> establishes a causal baseline: <em>what can be known at posting time?</em></li>
<li><strong>Model 2</strong> quantifies the power of <em>early engagement snowball effects</em>.</li>
<li>Combined, they tell a full story about Reddit virality mechanics.</li>
</ul>
<hr>
</section>
</section>
<section id="business-question-2-can-we-classify-the-emotional-tone-of-reddit-posts-as-positive-negative-or-neutral-to-understand-public-sentiment-at-scale" class="level2">
<h2 class="anchored" data-anchor-id="business-question-2-can-we-classify-the-emotional-tone-of-reddit-posts-as-positive-negative-or-neutral-to-understand-public-sentiment-at-scale">Business Question 2: Can we classify the emotional tone of Reddit posts as positive, negative, or neutral to understand public sentiment at scale?</h2>
<section id="problem-formulation-1" class="level3">
<h3 class="anchored" data-anchor-id="problem-formulation-1">Problem Formulation</h3>
<ul>
<li><strong>Task Type:</strong> Multi-class Classification (3 classes: Positive, Negative, Neutral)</li>
<li><strong>Target Variable:</strong> Sentiment label (positive/negative/neutral) derived from keyword-based labeling of text content</li>
<li><strong>Evaluation Metric:</strong> F1-Score (primary), Accuracy, Precision, Recall (secondary)</li>
</ul>
</section>
<section id="feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering">Feature Engineering</h3>
<p><strong>Features Used:</strong></p>
<ul>
<li>Text Preprocessing Features:</li>
</ul>
<p>Lowercased text with URLs and special characters removed Whitespace normalized and filtered to minimum 20 characters Stop words retained for context preservation</p>
<ul>
<li>TF-IDF Vectorization (1000 dimensions):</li>
</ul>
<p>Term Frequency: Word occurrence counts within each document Inverse Document Frequency: Weighting to emphasize distinctive words N-grams: Unigrams and bigrams (1-2 word sequences) captured</p>
<ul>
<li>Sentiment Keyword Indicators:</li>
</ul>
<p>Positive word count (16 keywords: love, great, excellent, amazing, perfect, etc.) Negative word count (16 keywords: hate, terrible, awful, worst, bad, etc.) Used for initial labeling, then learned implicitly by model</p>
</section>
<section id="model-performance" class="level3">
<h3 class="anchored" data-anchor-id="model-performance">Model Performance</h3>
<p>[Visualization: ROC curve, confusion matrix, etc.]</p>
<p><img src="../data/plots/ML_logistic_regression_confusion_matrix.png" class="img-fluid"> <img src="../data/plots/ML_logistic_regression_performance.png" class="img-fluid"></p>
<p><strong>Results:</strong></p>
<ul>
<li>Accuracy: 85.4</li>
<li>Precision:</li>
</ul>
<p>negative: 0.47 neutral: 0.87 positive: 0.80</p>
<ul>
<li>Recall:</li>
</ul>
<p>negative: 0.14 neutral: 0.96 positive: 0.62</p>
<ul>
<li>F1 Score:</li>
</ul>
<p>negative: 0.22 neutral: 0.91 positive: 0.7</p>
</section>
<section id="summary-1" class="level3">
<h3 class="anchored" data-anchor-id="summary-1">Summary</h3>
<p>The sentiment classification pipeline successfully demonstrates that Reddit posts can be automatically classified at massive scale with accuracy of 75-85%. The primary technical challenges include severe class imbalance (77.5% neutral vs 6.2% negative posts) causing model bias toward majority class predictions, keyword-based labeling that misses nuanced language like sarcasm and context-dependent sentiment. Negative sentiment proves most difficult to detect with only 60-68% expected recall due to data scarcity and subtle expression patterns that avoid explicit negative keywords, while neutral posts containing mixed signals or balanced reviews create classification ambiguity beyond bag-of-words features.</p>
<hr>
</section>
</section>
<section id="business-question-3-can-we-identify-inauthentic-promotional-accounts-versus-genuine-users-in-audio-product-discussions" class="level2">
<h2 class="anchored" data-anchor-id="business-question-3-can-we-identify-inauthentic-promotional-accounts-versus-genuine-users-in-audio-product-discussions">Business Question 3: Can we identify inauthentic promotional accounts versus genuine users in audio product discussions?</h2>
<section id="problem-formulation-2" class="level3">
<h3 class="anchored" data-anchor-id="problem-formulation-2">Problem Formulation</h3>
<ul>
<li><strong>Task Type:</strong> Binary Classification</li>
<li><strong>Target Variable:</strong> <code>is_suspicious</code> (1 = bot/promotional, 0 = authentic user)</li>
<li><strong>Evaluation Metrics:</strong> Accuracy, Precision, Recall, F1-Score, AUC-ROC, AUC-PR</li>
<li><strong>Dataset:</strong> 145,234 unique users across audio-related subreddits</li>
</ul>
<p><strong>Goal:</strong> Detect suspicious posting patterns indicating bots, promotional accounts, or astroturfing campaigns to ensure authentic consumer insights inform business decisions.</p>
<hr>
</section>
<section id="feature-engineering-user-behavioral-patterns" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering-user-behavioral-patterns">Feature Engineering: User Behavioral Patterns</h3>
<p>We analyze <strong>14 user-level features</strong> derived from posting behavior:</p>
<p><strong>Posting Volume Indicators:</strong> - <code>total_comments</code> - Overall activity level - <code>active_days</code> - Days with at least one comment - <code>comments_per_day</code> - Posting frequency - <code>activity_span_days</code> - Days between first and last comment</p>
<p><strong>Community Diversity Signals:</strong> - <code>subreddit_diversity</code> - Number of unique subreddits - Suspicious: Brand-focused accounts post only in one brand’s subreddit - Authentic: Users participate across multiple communities</p>
<p><strong>Temporal Pattern Analysis:</strong> - <code>posting_hour_variance</code> - Consistency in posting times - Suspicious: Bots post at identical times (low variance) - Authentic: Humans have irregular schedules (high variance) - <code>avg_posting_hour</code> - Average hour of activity</p>
<p><strong>Engagement Quality Metrics:</strong> - <code>avg_comment_score</code> - Average upvotes received - <code>score_variance</code> - Variance in comment reception - <code>upvoted_comments</code> - Count of positively-received comments - <code>upvote_rate</code> - Percentage of comments with &gt;1 upvote</p>
<p><strong>Text Pattern Signals:</strong> - <code>avg_comment_length</code> - Average characters per comment - <code>text_length_variance</code> - Consistency in comment length - <code>short_comment_rate</code> - Percentage of very brief comments (&lt;20 chars)</p>
<hr>
</section>
<section id="suspicious-user-labeling" class="level3">
<h3 class="anchored" data-anchor-id="suspicious-user-labeling">Suspicious User Labeling</h3>
<p>Users are flagged as suspicious if they exhibit any of:</p>
<ol type="1">
<li><strong>High-volume, low-diversity accounts:</strong> <code>total_comments &gt; 100</code> AND <code>subreddit_diversity &lt; 3</code></li>
<li><strong>Generic spam patterns:</strong> <code>short_comment_rate &gt; 0.7</code> AND <code>avg_comment_score &lt; 2</code></li>
<li><strong>Unnatural posting frequency:</strong> <code>comments_per_day &gt; 20</code></li>
<li><strong>Bot-like temporal consistency:</strong> <code>posting_hour_variance &lt; 1.0</code></li>
</ol>
<p><strong>Label Distribution:</strong> - Authentic users: 140,103 (96.5%) - Suspicious accounts: 5,131 (3.5%)</p>
<p><strong>Limitation:</strong> These labels reflect our heuristics, not verified bots. Model performance measures how well it learns these patterns, not true bot detection accuracy.</p>
<hr>
</section>
<section id="model-performance-results" class="level3">
<h3 class="anchored" data-anchor-id="model-performance-results">Model Performance Results</h3>
<p><strong>Algorithm:</strong> Random Forest (100 trees, max depth 8)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 22%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Score</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Accuracy</strong></td>
<td style="text-align: right;">99.52%</td>
<td>Correctly classifies 99.5% of users</td>
</tr>
<tr class="even">
<td><strong>Precision</strong></td>
<td style="text-align: right;">99.52%</td>
<td>99.5% of flagged accounts are actually suspicious</td>
</tr>
<tr class="odd">
<td><strong>Recall</strong></td>
<td style="text-align: right;">99.52%</td>
<td>Catches 99.5% of suspicious accounts</td>
</tr>
<tr class="even">
<td><strong>F1 Score</strong></td>
<td style="text-align: right;">99.52%</td>
<td>Excellent balance of precision and recall</td>
</tr>
<tr class="odd">
<td><strong>AUC-ROC</strong></td>
<td style="text-align: right;">0.9998</td>
<td>Near-perfect discrimination ability</td>
</tr>
<tr class="even">
<td><strong>AUC-PR</strong></td>
<td style="text-align: right;">0.9999</td>
<td>Robust even with class imbalance</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong> The model achieves <strong>near-perfect reproduction of rule-based patterns</strong> with minimal false positives/negatives. High performance indicates:</p>
<ol type="1">
<li>Features successfully capture the patterns defined by our heuristics</li>
<li>The model generalizes these patterns (not just memorizing exact thresholds)</li>
<li>Feature interactions beyond simple rules are being learned</li>
</ol>
<p><strong>Caveat:</strong> Performance is measured against rule-based labels, not ground-truth bot annotations. This represents an upper bound on detection capability.</p>
<p><strong>Confusion Matrix:</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data/plots/ml_bot_detection_confusion_matrix.png" class="img-fluid figure-img"></p>
<figcaption>Bot Detection Confusion Matrix</figcaption>
</figure>
</div>
<hr>
</section>
<section id="feature-importance-analysis" class="level3">
<h3 class="anchored" data-anchor-id="feature-importance-analysis">Feature Importance Analysis</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data/plots/ml_bot_detection_feature_importance.png" class="img-fluid figure-img"></p>
<figcaption>Feature Importance for Bot Detection</figcaption>
</figure>
</div>
<p><strong>Top 5 Most Predictive Features:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 20%">
<col style="width: 27%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th>Feature</th>
<th>Importance</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>posting_hour_variance</code></td>
<td>39.4%</td>
<td><strong>Temporal consistency is the strongest bot signal</strong></td>
</tr>
<tr class="even">
<td>2</td>
<td><code>activity_span_days</code></td>
<td>17.9%</td>
<td>Short-lived accounts are suspicious</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>active_days</code></td>
<td>15.7%</td>
<td>Bots have unnatural activity patterns</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>text_length_variance</code></td>
<td>9.2%</td>
<td>Repetitive comment lengths signal automation</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>total_comments</code></td>
<td>7.6%</td>
<td>Volume matters (bots post prolifically)</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="key-insights" class="level3">
<h3 class="anchored" data-anchor-id="key-insights">Key Insights</h3>
<p><strong>1. Temporal Patterns Are the Strongest Signal (39.4%)</strong> - Bots post on automated schedules with low hour variance - Humans have irregular activity patterns (work, sleep, weekends) - Example: Posts daily at 9am, 3pm, 9pm (variance &lt; 1.0) = suspicious</p>
<p><strong>2. Activity Longevity Matters (17.9%)</strong> - Promotional campaigns have short lifespans (days to weeks) - Authentic enthusiasts participate for months/years - Short <code>activity_span_days</code> separates flash campaigns from genuine users</p>
<p><strong>3. Text Consistency Reveals Automation (9.2%)</strong> - Bots post similar-length comments (templates, scripts) - Humans write varied lengths based on context - Low <code>text_length_variance</code> detects copy-paste behavior</p>
<p><strong>4. Subreddit Diversity is Less Important (0.6%)</strong> - Many authentic users are brand loyalists - Temporal and text patterns are better discriminators - Brand-only posting is necessary but not sufficient for detection</p>
<hr>
</section>
<section id="business-implications" class="level3">
<h3 class="anchored" data-anchor-id="business-implications">Business Implications</h3>
<p><strong>1. Protect Data Quality for Consumer Insights</strong> - Filter suspicious accounts before sentiment analysis - Apply bot detector to user IDs before aggregating feedback - Ensure reliable consumer insights by removing 3.5% bot contamination</p>
<p><strong>2. Community Trust &amp; Platform Health</strong> - Flag accounts with &gt;90% bot probability for moderator review - Implement automated rate limiting for suspicious patterns - Maintain authentic discussions in audio product communities</p>
<p><strong>3. Competitive Intelligence Applications</strong> - Detect competitor astroturfing campaigns - Identify coordinated promotion of specific brands - Track emergence of new promotional tactics</p>
<p><strong>4. Real-Time Monitoring System</strong> - Calculate 14 behavioral features for each user weekly - Run Random Forest model on all active users - Tiered response: High confidence (&gt;95%) → shadowban, Medium (80-95%) → manual review</p>
<hr>
</section>
<section id="summary-2" class="level3">
<h3 class="anchored" data-anchor-id="summary-2">Summary</h3>
<p><strong>Main Findings:</strong> - Developed rule-based suspicious behavior detection with <strong>99.5% model accuracy</strong> at reproducing patterns - <strong>Temporal patterns</strong> (posting hour variance) are the strongest distinguishing signal (39.4%) - <strong>Activity longevity</strong> separates promotional campaigns from genuine users (17.9%) - Model successfully learns feature interactions beyond simple threshold rules</p>
<p><strong>What This Demonstrates:</strong> - Behavioral features effectively distinguish suspicious patterns from organic users - Machine learning adds value by learning feature importance and combinations - Framework is ready for validation with ground-truth bot labels when available</p>
<p><strong>Business Value:</strong> - Provides baseline for identifying suspicious accounts in Reddit discussions - Feature importance guides manual review prioritization - Framework can be extended with verified bot examples for true validation</p>
<p><strong>Key Recommendation:</strong> Use this model as a <strong>first-pass filter</strong> to flag accounts for manual review. 99.5% accuracy reflects pattern learning, not verified bot detection. Validate flagged accounts manually before excluding from business analysis.</p>
<hr>
</section>
</section>
<section id="business-question-4-what-underlying-painpoint-clusters-exist-in-reddit-discussions-about-wireless-earbuds-and-how-do-these-clusters-differ-across-subreddits" class="level2">
<h2 class="anchored" data-anchor-id="business-question-4-what-underlying-painpoint-clusters-exist-in-reddit-discussions-about-wireless-earbuds-and-how-do-these-clusters-differ-across-subreddits">Business Question 4: What underlying painpoint clusters exist in Reddit discussions about wireless earbuds, and how do these clusters differ across subreddits?</h2>
<hr>
<section id="problem-formulation-3" class="level3">
<h3 class="anchored" data-anchor-id="problem-formulation-3">Problem Formulation</h3>
<ul>
<li><strong>Task Type:</strong> Clustering<br>
</li>
<li><strong>Input Features:</strong> 7 painpoint signals extracted from text
<ul>
<li>battery, anc, comfort, price, durability, connectivity, sound<br>
</li>
</ul></li>
<li><strong>Objective:</strong> Identify natural groupings of complaints and compare how subreddits differ in their dominant painpoint profiles.</li>
</ul>
<hr>
</section>
<section id="approach" class="level3">
<h3 class="anchored" data-anchor-id="approach">Approach</h3>
<p>We apply <strong>K-Means clustering</strong> to 147,025 painpoint vectors (comments + submissions).</p>
<section id="steps" class="level4">
<h4 class="anchored" data-anchor-id="steps">Steps:</h4>
<ol type="1">
<li>Load combined painpoint dataset<br>
</li>
<li>Evaluate cluster counts using:
<ul>
<li><strong>Elbow Method</strong><br>
<img src="../data/plots/ML_clustering_elbow_combined.png" class="img-fluid"></li>
<li><strong>Silhouette Score</strong><br>
<img src="../data/plots/ML_clustering_silhouette_combined.png" class="img-fluid"></li>
</ul></li>
<li>Select <strong>k = 9</strong> (best silhouette score)</li>
<li>Fit final K-Means<br>
</li>
<li>Visualize cluster centroids and subreddit distributions</li>
</ol>
<hr>
</section>
</section>
<section id="cluster-results" class="level3">
<h3 class="anchored" data-anchor-id="cluster-results">Cluster Results</h3>
<section id="best-number-of-clusters" class="level4">
<h4 class="anchored" data-anchor-id="best-number-of-clusters">Best Number of Clusters</h4>
<p><strong>Silhouette-selected k = 9</strong>, indicating strong separation in complaint patterns.</p>
</section>
<section id="cluster-centroids" class="level4">
<h4 class="anchored" data-anchor-id="cluster-centroids">Cluster Centroids</h4>
<p>Each cluster represents a dominant painpoint pattern. This heatmap shows the K-means cluster centers, where each row is a group of similar complaints and each cell reflects how often a specific painpoint (0 = rarely, 1 = almost always) appears in that cluster.”</p>
<p><img src="../data/plots/ML_cluster_centers_combined.png" class="img-fluid"></p>
<p>Examples: - Some clusters are dominated by <strong>sound complaints</strong>, others by <strong>battery</strong>, <strong>ANC</strong>, <strong>connectivity</strong>, or <strong>durability</strong>. - Several clusters show <strong>mixed patterns</strong>, such as <strong>battery + ANC</strong> or <strong>price + durability</strong>.</p>
<hr>
</section>
</section>
<section id="subreddit-level-patterns" class="level3">
<h3 class="anchored" data-anchor-id="subreddit-level-patterns">Subreddit-Level Patterns</h3>
<p>We compute how much each subreddit contributes to each cluster.</p>
<p><img src="../data/plots/ML_subreddit_cluster_heatmap_combined.png" class="img-fluid"></p>
<section id="key-observations" class="level4">
<h4 class="anchored" data-anchor-id="key-observations">Key Observations:</h4>
<ul>
<li><strong>audiophile</strong>, <strong>audio</strong> → High in <strong>sound-focused clusters</strong><br>
</li>
<li><strong>bluetooth</strong> → High in <strong>connectivity-focused clusters</strong><br>
</li>
<li><strong>BuyItForLife</strong>, <strong>Costco</strong>, <strong>running</strong> → Many <strong>durability/quality clusters</strong><br>
</li>
<li><strong>Android</strong>, <strong>GooglePixel</strong>, <strong>apple</strong> → Mixed <strong>battery + ANC</strong> complaint clusters</li>
</ul>
<p>This shows that each community has a distinct “complaint fingerprint.”</p>
<hr>
</section>
</section>
<section id="interpretation-insights-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-insights-1">Interpretation &amp; Insights</h3>
<section id="complaint-types-fall-into-9-natural-patterns." class="level4">
<h4 class="anchored" data-anchor-id="complaint-types-fall-into-9-natural-patterns.">1. Complaint types fall into ~9 natural patterns.</h4>
<p>Users consistently focus on a small set of core issues: sound, connectivity, battery, ANC, comfort, durability, and price.</p>
</section>
<section id="subreddit-communities-emphasize-different-painpoints." class="level4">
<h4 class="anchored" data-anchor-id="subreddit-communities-emphasize-different-painpoints.">2. Subreddit communities emphasize different painpoints.</h4>
<p>Technical subs care about <strong>connectivity</strong>, audiophile subs about <strong>sound</strong>, and lifestyle/value subs about <strong>durability</strong>.</p>
</section>
<section id="these-clusters-reflect-different-customer-expectations." class="level4">
<h4 class="anchored" data-anchor-id="these-clusters-reflect-different-customer-expectations.">3. These clusters reflect different customer expectations.</h4>
<p>Clustering reveals which communities prioritize premium sound, long-lasting gear, or reliable connectivity.</p>
<hr>
</section>
</section>
<section id="summary-3" class="level3">
<h3 class="anchored" data-anchor-id="summary-3">Summary</h3>
<p>Reddit discussions naturally group into <strong>9 painpoint clusters</strong>, each representing a distinct type of user dissatisfaction. These clusters vary significantly across subreddits, showing that each community has unique priorities (e.g., sound quality, connectivity reliability, durability, or price). This clustering provides a structured way to understand community-specific concerns and guide product or marketing strategies.</p>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>All ML code is in <code>code/ml/</code> directory. Models saved in <code>code/ml/models/</code>.</p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>DSAN 6000 Big Data Analytics Project</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>